language: python

matrix:
  include:
    - python: 2.6
    - python: 2.7
    - python: 3.3
    - python: 3.4
    - python: 3.5
    - python: pypy
    - python: pypy3
    - python: nightly

script: python setup.py test
